# Generated by Django 3.0.3 on 2020-02-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('item_status', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=50)),
                ('images', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('price_min', models.IntegerField()),
                ('price_max', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
    ]
