# Generated by Django 3.0.3 on 2020-02-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee_spider', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
