# Generated by Django 3.0.3 on 2020-02-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee_spider', '0002_auto_20200215_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='abandoned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='following',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
