# Generated by Django 3.0.3 on 2020-02-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee_spider', '0004_auto_20200215_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
