# Generated by Django 3.0.3 on 2020-02-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee_spider', '0005_item_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shopid',
            field=models.CharField(default='', max_length=20),
        ),
    ]
