# Generated by Django 3.0.3 on 2020-02-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee_spider', '0006_item_shopid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.CharField(default='', max_length=20),
        ),
    ]
