# Generated by Django 3.0.3 on 2020-02-18 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopee_spider', '0008_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tag_ling',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopee_spider.Tag'),
        ),
    ]
