# Generated by Django 3.0.3 on 2020-02-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee_spider', '0009_item_tag_ling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tag',
        ),
    ]
