# Generated by Django 3.0.3 on 2020-02-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee_spider', '0010_remove_item_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tag_ling',
            new_name='tag',
        ),
    ]
