# Generated by Django 3.0.3 on 2020-03-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee_spider', '0011_auto_20200218_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='liked_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
    ]
