# Generated by Django 3.0.3 on 2020-03-06 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopee_spider', '0012_auto_20200306_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='item',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
