# Generated by Django 3.0.3 on 2020-03-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee_spider', '0013_auto_20200306_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-modified',)},
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
